/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as HomeRouteImport } from './routes/home'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ShareRouteImport } from './routes/share'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as ProductIndexRouteImport } from './routes/product.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileAboutRouteImport } from './routes/profile.about'
import { Route as ProfileAccountRouteImport } from './routes/profile.account'
import { Route as ProfileBankRouteImport } from './routes/profile.bank'
import { Route as ProfileDownloadRouteImport } from './routes/profile.download'
import { Route as ProfileHistoryRouteImport } from './routes/profile.history'
import { Route as ProfileLogoutRouteImport } from './routes/profile.logout'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as ProfilePrivacyRouteImport } from './routes/profile.privacy'
import { Route as ProfileSecurityRouteImport } from './routes/profile.security'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as ProfileSupportRouteImport } from './routes/profile.support'
import { Route as ProfileTermsRouteImport } from './routes/profile.terms'
import { Route as ProfileWithdrawPasswordRouteImport } from './routes/profile.withdraw-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIndexRoute = ProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAboutRoute = ProfileAboutRouteImport.update({
  id: '/profile/about',
  path: '/profile/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAccountRoute = ProfileAccountRouteImport.update({
  id: '/profile/account',
  path: '/profile/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileBankRoute = ProfileBankRouteImport.update({
  id: '/profile/bank',
  path: '/profile/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileDownloadRoute = ProfileDownloadRouteImport.update({
  id: '/profile/download',
  path: '/profile/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHistoryRoute = ProfileHistoryRouteImport.update({
  id: '/profile/history',
  path: '/profile/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileLogoutRoute = ProfileLogoutRouteImport.update({
  id: '/profile/logout',
  path: '/profile/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/profile/notifications',
  path: '/profile/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePrivacyRoute = ProfilePrivacyRouteImport.update({
  id: '/profile/privacy',
  path: '/profile/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSecurityRoute = ProfileSecurityRouteImport.update({
  id: '/profile/security',
  path: '/profile/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSupportRoute = ProfileSupportRouteImport.update({
  id: '/profile/support',
  path: '/profile/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileTermsRoute = ProfileTermsRouteImport.update({
  id: '/profile/terms',
  path: '/profile/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileWithdrawPasswordRoute = ProfileWithdrawPasswordRouteImport.update({
  id: '/profile/withdraw-password',
  path: '/profile/withdraw-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/not-found': typeof NotFoundRoute
  '/recharge': typeof RechargeRoute
  '/records': typeof RecordsRoute
  '/register': typeof RegisterRoute
  '/share': typeof ShareRoute
  '/team': typeof TeamRoute
  '/transactions': typeof TransactionsRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/account': typeof ProfileAccountRoute
  '/profile/bank': typeof ProfileBankRoute
  '/profile/download': typeof ProfileDownloadRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/logout': typeof ProfileLogoutRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/support': typeof ProfileSupportRoute
  '/profile/terms': typeof ProfileTermsRoute
  '/profile/withdraw-password': typeof ProfileWithdrawPasswordRoute
  '/product/': typeof ProductIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/not-found': typeof NotFoundRoute
  '/recharge': typeof RechargeRoute
  '/records': typeof RecordsRoute
  '/register': typeof RegisterRoute
  '/share': typeof ShareRoute
  '/team': typeof TeamRoute
  '/transactions': typeof TransactionsRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/account': typeof ProfileAccountRoute
  '/profile/bank': typeof ProfileBankRoute
  '/profile/download': typeof ProfileDownloadRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/logout': typeof ProfileLogoutRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/support': typeof ProfileSupportRoute
  '/profile/terms': typeof ProfileTermsRoute
  '/profile/withdraw-password': typeof ProfileWithdrawPasswordRoute
  '/product': typeof ProductIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/not-found': typeof NotFoundRoute
  '/recharge': typeof RechargeRoute
  '/records': typeof RecordsRoute
  '/register': typeof RegisterRoute
  '/share': typeof ShareRoute
  '/team': typeof TeamRoute
  '/transactions': typeof TransactionsRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/account': typeof ProfileAccountRoute
  '/profile/bank': typeof ProfileBankRoute
  '/profile/download': typeof ProfileDownloadRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/logout': typeof ProfileLogoutRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/support': typeof ProfileSupportRoute
  '/profile/terms': typeof ProfileTermsRoute
  '/profile/withdraw-password': typeof ProfileWithdrawPasswordRoute
  '/product/': typeof ProductIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/home'
    | '/not-found'
    | '/recharge'
    | '/records'
    | '/register'
    | '/share'
    | '/team'
    | '/transactions'
    | '/wallet'
    | '/withdraw'
    | '/auth/login'
    | '/auth/register'
    | '/product/$id'
    | '/profile/about'
    | '/profile/account'
    | '/profile/bank'
    | '/profile/download'
    | '/profile/history'
    | '/profile/logout'
    | '/profile/notifications'
    | '/profile/privacy'
    | '/profile/security'
    | '/profile/settings'
    | '/profile/support'
    | '/profile/terms'
    | '/profile/withdraw-password'
    | '/product/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chat'
    | '/home'
    | '/not-found'
    | '/recharge'
    | '/records'
    | '/register'
    | '/share'
    | '/team'
    | '/transactions'
    | '/wallet'
    | '/withdraw'
    | '/auth/login'
    | '/auth/register'
    | '/product/$id'
    | '/profile/about'
    | '/profile/account'
    | '/profile/bank'
    | '/profile/download'
    | '/profile/history'
    | '/profile/logout'
    | '/profile/notifications'
    | '/profile/privacy'
    | '/profile/security'
    | '/profile/settings'
    | '/profile/support'
    | '/profile/terms'
    | '/profile/withdraw-password'
    | '/product'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/home'
    | '/not-found'
    | '/recharge'
    | '/records'
    | '/register'
    | '/share'
    | '/team'
    | '/transactions'
    | '/wallet'
    | '/withdraw'
    | '/auth/login'
    | '/auth/register'
    | '/product/$id'
    | '/profile/about'
    | '/profile/account'
    | '/profile/bank'
    | '/profile/download'
    | '/profile/history'
    | '/profile/logout'
    | '/profile/notifications'
    | '/profile/privacy'
    | '/profile/security'
    | '/profile/settings'
    | '/profile/support'
    | '/profile/terms'
    | '/profile/withdraw-password'
    | '/product/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  HomeRoute: typeof HomeRoute
  NotFoundRoute: typeof NotFoundRoute
  RechargeRoute: typeof RechargeRoute
  RecordsRoute: typeof RecordsRoute
  RegisterRoute: typeof RegisterRoute
  ShareRoute: typeof ShareRoute
  TeamRoute: typeof TeamRoute
  TransactionsRoute: typeof TransactionsRoute
  WalletRoute: typeof WalletRoute
  WithdrawRoute: typeof WithdrawRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ProductIdRoute: typeof ProductIdRoute
  ProfileAboutRoute: typeof ProfileAboutRoute
  ProfileAccountRoute: typeof ProfileAccountRoute
  ProfileBankRoute: typeof ProfileBankRoute
  ProfileDownloadRoute: typeof ProfileDownloadRoute
  ProfileHistoryRoute: typeof ProfileHistoryRoute
  ProfileLogoutRoute: typeof ProfileLogoutRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfilePrivacyRoute: typeof ProfilePrivacyRoute
  ProfileSecurityRoute: typeof ProfileSecurityRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileSupportRoute: typeof ProfileSupportRoute
  ProfileTermsRoute: typeof ProfileTermsRoute
  ProfileWithdrawPasswordRoute: typeof ProfileWithdrawPasswordRoute
  ProductIndexRoute: typeof ProductIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof ProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/about': {
      id: '/profile/about'
      path: '/profile/about'
      fullPath: '/profile/about'
      preLoaderRoute: typeof ProfileAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/account': {
      id: '/profile/account'
      path: '/profile/account'
      fullPath: '/profile/account'
      preLoaderRoute: typeof ProfileAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/bank': {
      id: '/profile/bank'
      path: '/profile/bank'
      fullPath: '/profile/bank'
      preLoaderRoute: typeof ProfileBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/download': {
      id: '/profile/download'
      path: '/profile/download'
      fullPath: '/profile/download'
      preLoaderRoute: typeof ProfileDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/history': {
      id: '/profile/history'
      path: '/profile/history'
      fullPath: '/profile/history'
      preLoaderRoute: typeof ProfileHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/logout': {
      id: '/profile/logout'
      path: '/profile/logout'
      fullPath: '/profile/logout'
      preLoaderRoute: typeof ProfileLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/profile/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/privacy': {
      id: '/profile/privacy'
      path: '/profile/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof ProfilePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/security': {
      id: '/profile/security'
      path: '/profile/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof ProfileSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/support': {
      id: '/profile/support'
      path: '/profile/support'
      fullPath: '/profile/support'
      preLoaderRoute: typeof ProfileSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/terms': {
      id: '/profile/terms'
      path: '/profile/terms'
      fullPath: '/profile/terms'
      preLoaderRoute: typeof ProfileTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/withdraw-password': {
      id: '/profile/withdraw-password'
      path: '/profile/withdraw-password'
      fullPath: '/profile/withdraw-password'
      preLoaderRoute: typeof ProfileWithdrawPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  HomeRoute: HomeRoute,
  NotFoundRoute: NotFoundRoute,
  RechargeRoute: RechargeRoute,
  RecordsRoute: RecordsRoute,
  RegisterRoute: RegisterRoute,
  ShareRoute: ShareRoute,
  TeamRoute: TeamRoute,
  TransactionsRoute: TransactionsRoute,
  WalletRoute: WalletRoute,
  WithdrawRoute: WithdrawRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ProductIdRoute: ProductIdRoute,
  ProfileAboutRoute: ProfileAboutRoute,
  ProfileAccountRoute: ProfileAccountRoute,
  ProfileBankRoute: ProfileBankRoute,
  ProfileDownloadRoute: ProfileDownloadRoute,
  ProfileHistoryRoute: ProfileHistoryRoute,
  ProfileLogoutRoute: ProfileLogoutRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfilePrivacyRoute: ProfilePrivacyRoute,
  ProfileSecurityRoute: ProfileSecurityRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileSupportRoute: ProfileSupportRoute,
  ProfileTermsRoute: ProfileTermsRoute,
  ProfileWithdrawPasswordRoute: ProfileWithdrawPasswordRoute,
  ProductIndexRoute: ProductIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
